package io.o2m.model;

public enum TypeMappingReason {
    NUMBER_UNSPECIFIED_PK,
    NUMBER_UNSPECIFIED_ID_PATTERN,
    NUMBER_UNSPECIFIED_DEFAULT,
    NUMBER_EXPLICIT_PS,
    NUMBER_EXPLICIT_INTEGER,
    NUMBER_CLAMPED,
    YAML_OVERRIDE,
    DEFAULT_TYPE_MAP,
    MYSQL_NATIVE,
    MANUAL_REVIEW
}
