<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.o2m</groupId>
        <artifactId>oracle2mysql</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>o2m-cli</artifactId>
    <dependencies>
        <dependency>
            <groupId>io.o2m</groupId>
            <artifactId>o2m-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.o2m</groupId>
            <artifactId>o2m-oracle</artifactId>
        </dependency>
        <dependency>
            <groupId>io.o2m</groupId>
            <artifactId>o2m-mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.o2m</groupId>
            <artifactId>o2m-translate</artifactId>
        </dependency>
        <dependency>
            <groupId>io.o2m</groupId>
            <artifactId>o2m-diff</artifactId>
        </dependency>
        <dependency>
            <groupId>io.o2m</groupId>
            <artifactId>o2m-migrate</artifactId>
        </dependency>
        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>io.o2m.cli.O2mApplication</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
